name: u-boot-tools
version: 1
summary: u-boot-tools 
description: mkimage with fit verification enabled
grade: stable
confinement: strict

apps:
  run: 
    command: mkimage

parts:
  u-boot-tools:
    plugin: nil
    source: git://git.denx.de/u-boot.git
    source-tag: v2017.11
    build-packages:
      - device-tree-compiler
      - libssl-dev
    override-build: |
      make dragonboard410c_defconfig
      echo "CONFIG_CMD_MD5SUM=y\nCONFIG_SYS_NO_FLASH=y\nCONFIG_FIT=y\nCONFIG_FIT_SIGNATURE=y\nCONFIG_RSA=y\nCONFIG_FIT_VERBOSE=y \
               \nCONFIG_FIT_ENABLE_SHA256_SUPPORT=y\n# CONFIG_SPL_RSA is not set\n# CONFIG_SPL_LOAD_FIT is not set \
               \n# CONFIG_FIT_BEST_MATCH is not set\nCONFIG_RSA_SOFTWARE_EXP=y" \
         >> .config
      make tools-only
      cp tools/mkimage $SNAPCRAFT_PART_INSTALL
